param_agent:
  weight_cost: 1
  weight_wt: 0
param_env:
  n_cloud_node: 2048
  n_job_queue_bck: 5
  n_job_queue_obs: 5
  n_on_premise_node: 512
  n_window: 100
  penalty_invalid_action: 0.1
  penalty_not_allocate: 0
param_job:
  job_is_constant: true
  job_trace_n_jobs: 32
  job_trace_path: job_trace/FY2024/scacctreq_202412_dec1_1000_jobs.csv
  job_type: 1
  max_n_required_nodes: 3
  max_processing_time: 3
  max_t: 10
  max_user_id: 8
  n_job_per_time: 4
  nb_jobs_per_user: 1
  user_increment: 1
param_simulation:
  folder_suffix: result
  multi_algorithm: true
  nb_episodes: 2000
  nb_max_episode_steps: -1
  nb_steps: 1
