#!/usr/bin/env bash
# 高速化(PCN_FAST_UPDATE)を本番Rayパイプラインで end-to-end 確認（短縮 NITER）。GPU は Ray 任せ。
set -u
cd /home/noguchi/scheduler-sim-for-cb
NITER="${1:-20}"
FAST="${2:-1}"
CFG=experiments/distributed_pcn/job_synthetic_pcn.yml
OUT="experiments/distributed_pcn/profile_b2_128_fast${FAST}"
rm -rf "$OUT"; mkdir -p "$OUT"
echo "[fast_check] NITER=$NITER FAST=$FAST OUT=$OUT START=$(date +%H:%M:%S)"
DISTRIBUTED_PCN_PROFILE=1 PCN_FAST_UPDATE=$FAST \
PCN_FOURIER_CMD=1 PCN_FOURIER_BANDS=4 PCN_FILM=1 \
DISTRIBUTED_PCN_CONFIG=$CFG DISTRIBUTED_PCN_JOBS=128 DISTRIBUTED_PCN_OUTPUT_DIR=$OUT \
SCHEDULER_OBS_URGENCY=1 \
DISTRIBUTED_PCN_PHASE1_HEURISTIC_THRESHOLDS=0,50,150,500 DISTRIBUTED_PCN_PHASE1_HEURISTIC_EPISODES=8 \
DISTRIBUTED_PCN_SUPERVISED_EPOCHS=50 DISTRIBUTED_PCN_N_ITERATIONS=$NITER \
DISTRIBUTED_PCN_INITIAL_EPISODES=32 DISTRIBUTED_PCN_EVAL_INTERVAL=9999 DISTRIBUTED_PCN_EVAL_SAMPLES=64 \
DISTRIBUTED_PCN_REPLAY_TX_BUDGET=1200000 \
PCN_TRAIN_KNEE_PF_WEIGHT=8 PCN_TRAIN_LOW_SLOPE_PF_WEIGHT=6 \
PCN_TRAIN_LOW_WAIT_PF_WEIGHT=10 PCN_TRAIN_LOW_WAIT_MAX=0 PCN_TRAIN_LOW_WAIT_FRAC=0.30 \
PCN_USE_AMP=0 PCN_OBS_LOG=1 \
PCN_PHASE1_SWEEP_TRAIN_WEIGHT=10 PCN_PF_COMMAND_ANCHORS=16 \
PCN_CHOOSE_COMMANDS_MODE=pf_archive DISTRIBUTED_PCN_CMD_OUTCOMES=1 \
PYTHONUNBUFFERED=1 .venv/bin/python -u -m src.distributed.distributed_pcn_event \
  --conditioning --mid-core --no-viz > "$OUT/train.log" 2>&1
echo "[fast_check] DONE=$(date +%H:%M:%S) exit=$?"
grep -aE 'PROFILE Phase3|フェーズ[123]完了|総経過|経過時間' "$OUT/train.log" | sed 's/\x1b\[[0-9;]*m//g' | tail -10